### ISSUE TITLE
html_url undefined when run from cron

### ISSUE THREAD

**Issue by al-mcluckie** [LuisGhz/simple-ms-teams-webhook#2]
Hello

I'm successfully using your notification script to send automated build notifications to our Teams dev channel, which has been received very well by everyone by the way - looks very professional, but find it errors if run from a cron schedule. I don't think it's anything I'm doing in setting it up but please let me know if it is. We have a physical remote Windows runner performing the actual build but I doubt that makes a difference.

My calling code (with redacted names) is:
```
on:
  # Run nightly builds @22:00 mon-fri on default 'develop' only
  schedule:
    - cron: "0 22 * * 1-5"

...

	- uses: luisghz/simple-ms-teams-webhook-notifier@v1-latest
	  if: failure()
	  with: 
		webhook_url: ${{ env.XXXX_NOTIFY_URI }}
		summary: "Autobuild Failed"
		theme-color: Error
		title: "XXXX Autobuild Failed   (${{env.XXXX_ACTOR}})"
		text: "For ${{env.XXXX_NOTIFY_BUILD}}"
		sections: |
		  - activityTitle: "[View build output](https://github.com/XXXX/actions/runs/${{ github.run_id }}) from ${{env.XXXX_BUILD_END}}"
			activitySubtitle: "Commit msg: **${{env.COMMIT_MSG}}**\n\nWorkflow and/or build error output files are available on GitHub."
			activityImage: "http://XXXX.png"
```

The workflow error output states:
```
Setup Ok
(node:10080) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'html_url' of undefined
    at new BuildCard (C:\actions-runner\_work\_actions\luisghz\simple-ms-teams-webhook-notifier\v1-latest\dist\index.js:13135:117)
    at C:\actions-runner\_work\_actions\luisghz\simple-ms-teams-webhook-notifier\v1-latest\dist\index.js:6394:27
    at Generator.next (<anonymous>)
    at fulfilled (C:\actions-runner\_work\_actions\luisghz\simple-ms-teams-webhook-notifier\v1-latest\dist\index.js:6348:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:10080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

and to my untrained js eye it looks like the html_url reference in C:\actions-runner\_work\_actions\luisghz\simple-ms-teams-webhook-notifier\v1-latest\dist\index.js is not available in the github context payload when run from a cron job.
Note: I'm not using the run-number-link in my script.

```
        this.regexReplacer = [
            { target: 'actor', replace: githubActor },
            { target: 'actor-url', replace: `https://github.com/${githubActor}` },
            { target: 'avatar-url', replace: `${process.env.avatar_url}` },
            { target: 'run-number-link', replace: `[#${githubContext.runNumber}](${githubContext.payload.repository.html_url}/actions/runs/${githubContext.runId})` }
        ];
```

Thanks
Al
